CREATE USER DW IDENTIFIED BY test;

GRANT ALL PRIVILEGES TO DW;

CREATE TABLE DW.TB_SALES (
    ID NUMBER,
    DT_SALES DATE,
    ID_PAYMENT_TYPE NUMBER(10),
    ID_CUSTOMER NUMBER(20),
    NM_PRODUCT VARCHAR2(100),
    VL_AMOUNT NUMBER(10,2),
    NM_PAYMENT_TYPE VARCHAR2(50),
    NM_CUSTOMER VARCHAR2(100),
    DT_PROCESSING DATE
);