class KafkaEnum():
    FORMAT = "kafka"
    BOOTSTRAP_SERVERS = "localhost:9092"
    TOPIC = 'sales'
    OFFSET_RESET_START_OFFSET = "earliest"
    TOPIC_LOG = "log-monitor"
    AUTHORIZATION_CLIENT_ID = "sales"
    GROUP_ID = "sales"
    SESSION_TIMEOUT_MS = 30000
    HEARTBEAT_INTERVAL_MS = 3000
    REQUEST_TIMEOUT = 40000
    CONNECTION_MAX_IDLE_MS = 540000
    POOL_TIMEOUT_MS = 512
    FAIL_ON_DATA_LOSS = True
    NUMBER_RETRIES = 3
    RETRIES_INTERVAL_MS = 1000
    MAX_OFFSETS_PER_TRIGGER = 1000
    MIN_BATCHES_RETAIN = 100
